# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  theme: catppuccin-mocha
  image_protocol: auto
  terminal_font_size: 24
